name: Build Rust Qalendar API Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://postgres:password@localhost:5432/qalendar_test

jobs:
  check-sqlx:
    name: Check SQLx macros
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: qalendar_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-toolchain@v1
        with:
          toolchain: stable

      - name: Install SQLx CLI
        run: cargo install sqlx-cli --no-default-features --features postgres

      - name: Wait for Postgres to be ready
        run: sleep 5

      - name: Run schema SQL
        run: psql "$DATABASE_URL" -f sql/setup.sql

      - name: Check SQLx queries
        run: cargo sqlx prepare --check

  build-windows:
    name: Build Windows Binary
    runs-on: windows-latest
    needs: check-sqlx

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --verbose

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: qalendar-api.exe
          path: target/debug/qalendar-api.exe
