name: Build Rust Qalendar API Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --verbose

      # - name: Run tests
      #   run: cargo test --verbose

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: qalendar-api.exe
          path: target/debug/qalendar-api.exe
